# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[],
    hiddenimports=[
        # Selenium
        'selenium',
        'selenium.webdriver',
        'selenium.webdriver.chrome',
        'selenium.webdriver.chrome.webdriver',
        'selenium.webdriver.chrome.service',
        'selenium.webdriver.chrome.options',
        'selenium.webdriver.common.by',
        'selenium.webdriver.common.keys',
        'selenium.webdriver.support',
        'selenium.webdriver.support.ui',
        'selenium.webdriver.support.expected_conditions',
        'selenium.common.exceptions',
        # Webdriver manager
        'webdriver_manager',
        'webdriver_manager.chrome',
        # Openpyxl
        'openpyxl',
        'openpyxl.styles',
        'openpyxl.utils',
        # Requests
        'requests',
        'requests.adapters',
        'urllib3',
        # XML
        'xml',
        'xml.etree',
        'xml.etree.ElementTree',
        # Tkinter
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        'tkinter.filedialog',
        'tkinter.simpledialog',
        # Concurrent
        'concurrent',
        'concurrent.futures',
        'queue',
        # App modules
        'auth',
        'updater',
        'preferencias',
        'splash',
        'winsound',
        'login',
        'app',
        'painel_master',
        'notificacao',
        'excel_writer',
        'site_scraper',
        'xml_parser',
        # Outros
        'threading',
        'socket',
        'ssl',
        'smtplib',
        'email',
        'email.mime',
        'email.mime.text',
        'email.mime.multipart',
        'hashlib',
        'hmac',
        'secrets',
        'json',
        're',
        'lxml',
        'lxml.etree',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='CPB_Alocacao',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='app_icon.ico',
)
